version: "3.7"
services:
  dashboard:
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/aedigital/interface/node_modules"
      - ".:/aedigital"
    networks:
      - strapi