def baseCommand = '--all'
def affectedApps = []

pipeline {
  {
  agent none
  }
  parameters {
    string(
      name: 'affectedBase',
      defaultValue: '',
      description: 'Base command for nx affected; use --base={Commit SHA} or --all.'
    )
  }
  stages {
    stage('Prepare') {
                agent {
           node {      
            label 'node12-dotnet5'
            }
          }
      steps {
        checkout scm
        sh 'npm ci'
        script {
          if (params.affectedBase) {
            baseCommand = affectedBase
          } else if (env.GIT_PREVIOUS_SUCCESSFUL_COMMIT) {
            baseCommand = "--base=${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}"
          }

          affectedApps = sh (
            script: "npx nx affected:apps --plain ${baseCommand}",
            returnStdout: true
          ).split()
        }
        echo "Building with base ${baseCommand} and affected apps: ${affectedApps.join(', ')}"
      }
    }
    stage('Lint') {
      agent {
           node {      
            label 'node12-dotnet5'
            }
          }
      steps {
        sh "npx nx affected --target=lint ${baseCommand} --parallel"
      }
    }
    stage('Test') {
      agent {
           node {      
            label 'node12-dotnet5'
            }
          }
      steps {
        sh "npx nx affected --target=test ${baseCommand} --parallel"
      }
    }
    stage('Build') {
      agent {
           node {      
            label 'node12-dotnet5'
            }
          }
      steps {
        sh "npx nx affected --target=build ${baseCommand} --parallel --configuration=production"
        script {
          openshift.withCluster() {
            openshift.withProject('planmp-tools') {
              affectedApps.each { affected ->
                def bc = openshift.selector("bc", affected)
                if ( bc.exists() ) {
                  bc.startBuild("--from-dir=.", "--wait", "--follow")
                }
              }
            }
          }
        }
      }
    }
    stage('Deploy Dev') {
      input {
        message "Promote to Dev?"
      }
      agent {
           node {      
            label 'node12-dotnet5'
            }
          }
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject('planmp-tools') {
              affectedApps.each { affected ->
                def is = openshift.selector("is", "${affected}")
                if ( is.exists() ) {
                  openshift.tag("${affected}:latest", "${affected}:dev")
                }
              }
            }
          }
        }
        script {
          openshift.withCluster() {
            openshift.withProject('planmp-dev') {
              affectedApps.each { affected ->
                def dc = openshift.selector("dc", "${affected}")
                if ( dc.exists() ) {
                  def rm = dc.rollout()
                  rm.latest()
                  rm.status()
                }
              }
            }
          }
        }
      }
    }
stage('Smoke Test'){
            agent {
           node {      
            label 'node12-cypress'
            }
          }
      steps {
 
 sh "npx nx e2e planmp-e2e -- --spec=**/src/integration/smoke-test/* --browser chrome --headless=true " 

 }
  }
  }
}
